In [110]:
import numpy as np
import matplotlib.pyplot as plt

In [149]:
X = np.array([
    [0.7,23000,43],
    [0.5,23500,39],
    [0.3,20000,25],
    [0.5,30000,41],
    [0.6,26500,44]
])

In [150]:
y = np.array(
    [64796.4, 70316, 59885.6, 89806, 79291.2])


In [151]:
def serror(X,Y,w,w0):
    s = 0
    for i in range(len(X)):
        x = X[i]
        y = Y[i]
        error = (y-(np.dot(w,x)+w0))**2
        s += error
    return s

In [152]:
w = np.array([1,1,1])
w0 = 0

serror(X,Y,w,w0)

11874171697.44

In [153]:
w = np.array([2,3,-5])
w0 = 10

serror(X,Y,w,w0)

15999999.999999942

In [154]:
w = np.array([1,1,1]) #pesos
w0 = 0 #bias

In [155]:
#algoritmo ingenuo aleatorio

for t in range(1000):
    #peso primo
    wp = w + np.random.uniform(-1,1,len(w))
    #bias primo
    w0p = w0 + np.random.uniform(-1,1)
    #suma de error
    ew = serror(X,Y,w,w0)
    #suma de error prima
    ewp = serror(X,Y,wp,w0p)
    if ewp < ew:
        w = wp 
        w0 = w0p

In [156]:
w


array([ 2.6182972 ,  2.96514868, -2.13522263])

In [157]:
w0

-1.8990309521619155

In [158]:
ew

13417243.89367049

In [159]:
ewp

1580751372.573016

In [ ]:
#Regresion Lineal con libreria

In [160]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()

reg.fit(X,y)
reg.coef_, reg.intercept_

(array([-3.26993086e+04,  2.80437482e+00,  5.50831503e+02]),
 -316.8698060941824)

In [162]:
reg.predict([[0.7,22000,41],
           [0.2,1800,35]])

array([61073.95181966, 17470.24573503])